<?xml version="1.0"?>
<robot name="grips" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- Import common macros-->
  <xacro:include filename="$(find grips_description)/urdf/common.xacro" />
  <!-- Import materials for rviz-->
  <xacro:include filename="$(find grips_description)/urdf/materials.xacro" />
  <!-- Import robot without gripper -->
  <xacro:include filename="$(find grips_description)/urdf/grips_macro.xacro" />
  <!-- Import ft sensor -->
  <xacro:include filename="$(find grips_description)/urdf/ft_sensor.xacro" />
  <!-- Import imu sensor -->
  <xacro:include filename="$(find grips_description)/urdf/imu_sensor.xacro" />
  <!-- Import robotiq s model -->
  <xacro:include filename="$(find robotiq_s_model_visualization)/cfg/s-model_articulated.xacro" />
  
  <property name="robot_name" value="" />
  
  <!-- Create the grips robot -->
  <grips_robot name="${robot_name}"/>
  <!-- Add the ft_sensor -->
  <ft_sensor name="${robot_name}" parent="${robot_name}end_effector"/>
  <!-- Add the imu_sensor -->
  <imu_sensor prefix="${robot_name}" parent="${robot_name}end_effector">
    <origin xyz="0 0.13 ${board_z_size+63.635e-3}" rpy="0 0 0" />
  </imu_sensor>
  <!-- Add robotiq hand -->
  <s-model_fixed prefix="${robot_name}"/>
  <gazebo reference="${robot_name}palm">
    <material>Gazebo/FlatBlack</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  
  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world" />
  <joint name="anchor" type="fixed">
    <origin xyz="0 0 0.001" rpy="0 0 0" />
    <parent link="world" />
    <child link="base_link" />
  </joint>  
  <!-- Used for fixing Robotiq to the FT sensor -->
  <joint name="robotiq_anchor" type="fixed">
    <origin xyz="0 54e-3 0" rpy="0 0 0" />
    <parent link="${robot_name}ft_end_effector" />
    <child link="${robot_name}palm" />
  </joint>  
  
  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/grips</robotNamespace>
    </plugin>
  </gazebo>
  
  <!--ROS P3D odometry -->
	<gazebo>
		<plugin name="imu_sensor_odometry" filename="libgazebo_ros_p3d.so">
			<robotNamespace>/grips</robotNamespace>
			<bodyName>end_effector</bodyName>
			<topicName>imu_odom</topicName>
			<frameName>base_link</frameName>
			<xyzOffset>0 0 0</xyzOffset>
			<rpyOffset>0 0 0</rpyOffset>
			<gaussianNoise>0.0</gaussianNoise>
			<updateRate>1000</updateRate>
		</plugin>
	</gazebo>
	<!-- ROS Force Plugin -->
	<gazebo>
		<plugin name="ext_force_publisher" filename="libgazebo_ros_force.so">
			<robotNamespace>/grips</robotNamespace>
			<bodyName>end_effector</bodyName>
			<topicName>ext_force</topicName>
		</plugin>
	</gazebo>
	<!-- ROS F3D Plugin -->
	<gazebo>
		<plugin name="ext_force_listener" filename="libgazebo_ros_f3d.so">
			<robotNamespace>/grips</robotNamespace>
			<topicName>extft_data</topicName>
			<bodyName>end_effector</bodyName>
			<frameName>base_link</frameName>
		</plugin>
    </gazebo>
  
</robot>
